/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void checkbox1_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox1:564702:
  //println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
  if (balance == 0)
    balance = 1;
  else
    balance = 0;
} //_CODE_:checkbox1:564702:

public void slider4_change1(GSlider source, GEvent event) { //_CODE_:slider4:447907:
  //println("slider4 - GSlider >> GEvent." + event + " @ " + millis());
  eyeR = slider4.getValueF();
} //_CODE_:slider4:447907:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:463985:
  //println("button3 - GButton >> GEvent." + event + " @ " + millis());
  thetaDes = PI/2;
} //_CODE_:button3:463985:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:769683:
  //println("button4 - GButton >> GEvent." + event + " @ " + millis());
  thetaDes = PI;
} //_CODE_:button4:769683:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:915853:
  //println("button5 - GButton >> GEvent." + event + " @ " + millis());
  thetaDes = 0;
} //_CODE_:button5:915853:

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  slider4 = new GSlider(this, 884, 20, 100, 40, 10.0);
  slider4.setLimits(800.0, 0.0, 2000.0);
  slider4.setNumberFormat(G4P.DECIMAL, 2);
  slider4.setOpaque(false);
  slider4.addEventHandler(this, "slider4_change1");
  label4 = new GLabel(this, 894, 5, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("zoom");
  label4.setOpaque(false);
  button3 = new GButton(this, 193, 652, 20, 20);
  button3.setText("L");
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 167, 652, 20, 20);
  button4.setText("U");
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 142, 652, 20, 20);
  button5.setText("D");
  button5.addEventHandler(this, "button5_click1");
}

// Variable declarations 
// autogenerated do not edit
GSlider slider1; 
GLabel label1; 
GSlider slider4; 
GLabel label4;
GButton button3; 
GButton button4; 
GButton button5; 